#### scraping and crawling

In [2]:
pip install requests bs4

Requirement already satisfied: requests in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (2.32.3)Note: you may need to restart the kernel to use updated packages.

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from requests) (3.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from requests) (2024.8.30)
Requirement already satisfied: idna<4,>=2.5 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from requests) (3.10)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Collecting soupsieve>=1.6.1
  Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from beautifulsoup4->bs4) (4.12.2)
Installing collected packages: soupsieve, beautifulsoup4, bs4
Successfully installed beautifulsoup4-4.15.0 bs4-0.0.2 soupsieve-2.8.4

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'c:\Users\E L I T E B O O K\OneDrive\Documents\SEM 3\AI\.venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [3]:
import requests
from bs4 import BeautifulSoup

url = "https://www.batamnews.co.id/berita/1"
response = requests.get(url)
# soup = BeautifulSoup(response.text, "html.parser")

print(response)

<Response [200]>

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

base_url_links = []
for i in range(1, 2):
    base_url = f"https://www.batamnews.co.id/berita/{i}"
    base_url_links.append(base_url)

links = []
for url in base_url_links:
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    # find all article links
    for a in soup.find_all("a", href=True):
        href = a["href"]
        # filter only news articles
        if "berita-" in href and href.endswith(".html"):
            # make full URL
            if href.startswith("http"):
                full_url = href
            else:
                full_url = "https://www.batamnews.co.id/" + href
            links.append(full_url)



links = list(set(links))

print("Article links have been obtained!")

titles = []
content = []
published_date = []
news_type = []
for news_links in links:
    response = requests.get(news_links)
    soup = BeautifulSoup(response.text, 'html.parser')

    get_news_type_div = soup.find('div', class_='post-date')
    get_news_type = get_news_type_div.find_all('a')
    news_type.append(get_news_type[1].text)

    get_titles = soup.find_all('h1')
    titles.append(get_titles[2].text)

    get_content = soup.find_all('p')
    article = ' '.join([p.get_text(strip=True) for p in get_content])
    content.append(article)

    get_published_date = soup.find_all('div', itemprop='datePublished')
    published_date.append(get_published_date[0].text)

print("Data has been obtained")

df = pd.DataFrame({
    'title' : titles,
    'news_type' : news_type,
    'content' : content,
    'published_date' : published_date,
    'links' : links
})

print("Data saved to csv!")

Article links have been obtained!
Data has been obtained
Data saved to csv!

In [5]:
df.to_csv('crawling_batamnews_vs2.csv')
df

,title,news_type,content,published_date,links
0,Oknum Guru Honorer Anambas Cabuli Murid SD 2 K...,Kriminalitas,Copyright 2014 -batamnews.co.idAll rights res...,"Kamis, 18 Juni 2026 - 10:01 WIB",https://www.batamnews.co.id/berita-128168-oknu...
1,Kecelakaan Batuaji: Pengendara Motor Wanita Kr...,Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Minggu, 14 Juni 2026 - 18:40 WIB",https://www.batamnews.co.id/berita-128107-kece...
2,"Prakiraan Cuaca Batam, Siang hingga Sore Berpo...",Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Kamis, 18 Juni 2026 - 08:13 WIB",https://www.batamnews.co.id/berita-128166-prak...
3,"Kritik Soal Pembangunan di Belakangpadang, Sek...",Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Senin, 15 Juni 2026 - 09:44 WIB",https://www.batamnews.co.id/berita-128112-krit...
4,Tahun Baru Hijriah 1448 H dan Momentum Menata ...,Opini,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 09:35 WIB",https://www.batamnews.co.id/berita-128146-tahu...
5,Turis Malaysia Dituding Tak Bayar Usai Makan d...,Kuliner,Copyright 2014 -batamnews.co.idAll rights res...,"Senin, 18 Mei 2026 - 14:12 WIB",https://www.batamnews.co.id/berita-127536-turi...
6,Ribuan Warga Pulau Kasu Kepung Kantor LSM LIRA...,Hukum,Copyright 2014 -batamnews.co.idAll rights res...,"Senin, 15 Juni 2026 - 12:40 WIB",https://www.batamnews.co.id/berita-128119-ribu...
7,PKP Hadirkan Promo Extra Time di Pameran PKP S...,Properti,Copyright 2014 -batamnews.co.idAll rights res...,"Jumat, 05 Juni 2026 - 11:16 WIB",https://www.batamnews.co.id/berita-127893-pkp-...
8,Enam Tersangka Kecelakaan Kerja PT ASL Shipyar...,Hukum,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 17:37 WIB",https://www.batamnews.co.id/berita-128157-enam...
9,"Roby Kurniawan Kunjungi BPJN Kepri, Bahas Peni...",Kepulauan Riau,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 21:58 WIB",https://www.batamnews.co.id/berita-128164-roby...
10,"Data SPMB Diduga Bocor, Kadiskominfo Batam: Or...",Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 17:47 WIB",https://www.batamnews.co.id/berita-128159-data...
11,"RDP Bersama Komisi VI DPR RI, BP Batam Paparka...",BP Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Kamis, 18 Juni 2026 - 08:25 WIB",https://www.batamnews.co.id/berita-128167-rdp-...
12,Tips Belanja Online untuk Dapatkan Barang Berk...,Batam Shopping,Copyright 2014 -batamnews.co.idAll rights res...,"Sabtu, 27 Juli 2024 - 10:45 WIB",https://www.batamnews.co.id/berita-113302-tips...
13,"Hanya Segelintir Anggota Hadir, Paripurna Pert...",Politik,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 19:57 WIB",https://www.batamnews.co.id/berita-128161-hany...
14,Respons Sejumlah Organisasi Mahasiswa di Kepri...,Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Sabtu, 13 Juni 2026 - 08:02 WIB",https://www.batamnews.co.id/berita-128076-resp...
15,58 Personel Polres Anambas Dikerahkan Amankan ...,Kepulauan Riau,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 18:58 WIB",https://www.batamnews.co.id/berita-128160-58-p...
16,Cara Daftar Program Pemagangan Jepang dan Pela...,Lowongan Kerja,Copyright 2014 -batamnews.co.idAll rights res...,"Minggu, 14 Juni 2026 - 15:22 WIB",https://www.batamnews.co.id/berita-128103-cara...
17,"Digelapkan Rp340 Juta Uang Tagihan Telur, Sopi...",Hukum,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 17:40 WIB",https://www.batamnews.co.id/berita-128158-dige...
18,Penataan UMKM Mega Legenda: BP Batam Beri Teng...,BP Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Senin, 15 Juni 2026 - 16:15 WIB",https://www.batamnews.co.id/berita-128123-pena...
19,"Urai Kemacetan, Pemko Batam Mulai Bangun Jalan...",Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 11:37 WIB",https://www.batamnews.co.id/berita-128148-urai...
20,Besan Kapolda Kepri Jadi Komisaris Baru Bukala...,Ekonomi,Copyright 2014 -batamnews.co.idAll rights res...,"Sabtu, 13 Juni 2026 - 20:45 WIB",https://www.batamnews.co.id/berita-128091-besa...
21,"LIRA Soroti Proyek Rp4,2 Miliar di Pulau Kasu,...",Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 08:48 WIB",https://www.batamnews.co.id/berita-128145-lira...
22,"Tergiur Upah Rp50 Juta per Paket, Dua Kurir Sa...",Kriminalitas,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 22:08 WIB",https://www.batamnews.co.id/berita-128165-terg...
23,"iPhone 18 Resmi Dibekali RAM 12 GB, Siri AI Ma...",Tekno,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 20:28 WIB",https://www.batamnews.co.id/berita-128162-ipho...
24,Polda Kepri Tangkap Pencuri Penutup Drainase d...,Kriminalitas,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 21:51 WIB",https://www.batamnews.co.id/berita-128163-pold...
25,Wali Kota Batam Tegaskan Ranperda LAM Harus Ja...,Pemko Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Senin, 20 April 2026 - 17:56 WIB",https://www.batamnews.co.id/berita-126923-wali...
26,"Sekda Ronny Kartika Buka Job Fair Bintan 2026,...",Advertorial,Copyright 2014 -batamnews.co.idAll rights res...,"Jumat, 12 Juni 2026 - 20:00 WIB",https://www.batamnews.co.id/berita-128068-sekd...
27,Peneliti Anonymous Sudah Peringatkan Celah SPM...,Batam,Copyright 2014 -batamnews.co.idAll rights res...,"Rabu, 17 Juni 2026 - 17:29 WIB",https://www.batamnews.co.id/berita-128156-pene...
28,Jadwal dan Rangkaian Acara Kemilau Nusantara K...,Wisata,Copyright 2014 -batamnews.co.idAll rights res...,"Minggu, 14 Juni 2026 - 10:03 WIB",https://www.batamnews.co.id/berita-128098-jadw...
29,"ERA, Newly set up by the former Sunseap’s co-f...",Batamnews English,Copyright 2014 -batamnews.co.idAll rights res...,"Sabtu, 01 November 2025 - 11:47 WIB",https://www.batamnews.co.id/berita-123347-era-...

#### importing data

In [1]:
#baca hasil crawling
import pandas as pd

df = pd.read_csv('crawling_batamnews.csv')

In [2]:
#processing text: hapus kalimat berulang di setiap artikel
df['content'] = df['content'].str.replace(
    'Copyright  2014 -batamnews.co.idAll rights reservedDikelola dan Dikembangkan Oleh :PT. Batam Media Siber',
   '', regex=False
)

#buat kolom baru: title + content artikel
df['full_text'] = df['title'] + '' + df['content']
df['full_text']

df[['content', 'title', 'full_text']].head()

,content,title,full_text
0,Login untuk menyimpan artikel favorit kamu B...,PKP EXPO Hadirkan Promo BBM di Grand Batam Mall,PKP EXPO Hadirkan Promo BBM di Grand Batam Mal...
1,"Kapolsek Kawasan Bandara Hang Nadim Batam, Ip...",Iptu Rifa Carolina Dilantik Jadi Kapolsek Band...,Iptu Rifa Carolina Dilantik Jadi Kapolsek Band...
2,"Home Stay Baba’s Batam Kota, Terbakar, 5 Unit...",Kebakaran Home Stay Baba’s di Pasar Dotamana B...,Kebakaran Home Stay Baba’s di Pasar Dotamana B...
3,"Wali Kota Batam, Amsakar Achmad saat menerima...",Wali Kota Batam Tegaskan Ranperda LAM Harus Ja...,Wali Kota Batam Tegaskan Ranperda LAM Harus Ja...
4,Petugas menyita sejumlah barang bukti berupa ...,Penggerebekan Apartemen Baloi View Batam: Ratu...,Penggerebekan Apartemen Baloi View Batam: Ratu...

In [3]:
import re

def clean_text(text):
    #lowercase
    text = text.lower()

    #remove any url
    text = re.sub(r'http\S+|www\S+', '', text)

    #remove punctuation
    text = re.sub(r'[^\w\s]', '', text)

    #remove numbers
    text = re.sub(r'\d+', '', text)

    #remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df['clean_content'] = df['content'].apply(clean_text)
df['clean_title'] = df['title'].apply(clean_text)
df['clean_full_text'] = df['full_text'].apply(clean_text)
df[['content', 'clean_content', 'title', 'clean_title', 'full_text', 'clean_full_text']].head(2)

,content,clean_content,title,clean_title,full_text,clean_full_text
0,Login untuk menyimpan artikel favorit kamu B...,login untuk menyimpan artikel favorit kamu bat...,PKP EXPO Hadirkan Promo BBM di Grand Batam Mall,pkp expo hadirkan promo bbm di grand batam mall,PKP EXPO Hadirkan Promo BBM di Grand Batam Mal...,pkp expo hadirkan promo bbm di grand batam mal...
1,"Kapolsek Kawasan Bandara Hang Nadim Batam, Ip...",kapolsek kawasan bandara hang nadim batam iptu...,Iptu Rifa Carolina Dilantik Jadi Kapolsek Band...,iptu rifa carolina dilantik jadi kapolsek band...,Iptu Rifa Carolina Dilantik Jadi Kapolsek Band...,iptu rifa carolina dilantik jadi kapolsek band...

In [4]:
df['published_date'] = df['published_date'].str.extract(r'(\d{2} [A-Za-z]+ \d{4})')
df['published_date']

0          01 Mei 2026
1          07 Mei 2026
2          10 Mei 2026
3        20 April 2026
4          06 Mei 2026
5          06 Mei 2026
6          11 Mei 2026
7          09 Mei 2026
8        23 Maret 2026
9          07 Mei 2026
10    01 November 2025
11         10 Mei 2026
12         11 Mei 2026
13         11 Mei 2026
14         11 Mei 2026
15         11 Mei 2026
16         11 Mei 2026
17         09 Mei 2026
18    22 Februari 2026
19         11 Mei 2026
20         07 Mei 2026
21        27 Juli 2024
22         11 Mei 2026
23         06 Mei 2026
24         06 Mei 2026
25         11 Mei 2026
26         06 Mei 2026
27         07 Mei 2026
28         08 Mei 2026
29         11 Mei 2026
30         11 Mei 2026
Name: published_date, dtype: object

#### traditional text processing

In [53]:
#tokenization
from nltk.tokenize import word_tokenize

def tokenization(text):
    tokens = word_tokenize(text)
    return tokens

df['tokenize_content'] = df['clean_content'].apply(tokenization)
df['tokenize_title'] = df['clean_title'].apply(tokenization)
df['tokenize_full_text'] = df['clean_full_text'].apply(tokenization)
df[['tokenize_content', 'tokenize_title', 'tokenize_full_text']].head(2)

,tokenize_content,tokenize_title,tokenize_full_text
0,"[login, untuk, menyimpan, artikel, favorit, ka...","[pkp, expo, hadirkan, promo, bbm, di, grand, b...","[pkp, expo, hadirkan, promo, bbm, di, grand, b..."
1,"[kapolsek, kawasan, bandara, hang, nadim, bata...","[iptu, rifa, carolina, dilantik, jadi, kapolse...","[iptu, rifa, carolina, dilantik, jadi, kapolse..."

In [59]:
#stopword removal (dan, yang di, ke, the, is)
from nltk.corpus import stopwords

def stopword_removal(text):
    stop_words = set(stopwords.words('indonesian'))
    filtered_text = [w for w in text if w not in stop_words]
    return filtered_text

df['stopword_removal_content'] = df['tokenize_content'].apply(stopword_removal)
df['stopword_removal_title'] = df['tokenize_title'].apply(stopword_removal)
df['stopword_removal_full_text'] = df['tokenize_full_text'].apply(stopword_removal)
df[['stopword_removal_content', 'stopword_removal_title', 'stopword_removal_full_text']].head(2)

,stopword_removal_content,stopword_removal_title,stopword_removal_full_text
0,"[login, menyimpan, artikel, favorit, batam, ba...","[pkp, expo, hadirkan, promo, bbm, grand, batam...","[pkp, expo, hadirkan, promo, bbm, grand, batam..."
1,"[kapolsek, kawasan, bandara, hang, nadim, bata...","[iptu, rifa, carolina, dilantik, kapolsek, ban...","[iptu, rifa, carolina, dilantik, kapolsek, ban..."

In [63]:
#jumlah kata sebelum dan sesudah stopword removal
print(len(df['tokenize_content'][1]))
print(len(df['stopword_removal_content'][1]))

314
229

In [ ]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def stemming(text):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    return [stemmer.stem(word) for word in text]

df['stemming_content'] = df['stopword_removal_content'].apply(stemming)
df['stemming_title'] = df['stopword_removal_title'].apply(stemming)
df['stemming_full_text'] = df['stopword_removal_full_text'].apply(stemming)
df[['stemming_content', 'stemming_removal_title', 'stemming_removal_full_text']].head(2)

#### modern text processing + bangun llm sendiri pake transformer

In [1]:
pip install transformers torch sentencepiece

Requirement already satisfied: transformers in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (5.8.0)
Collecting torch
  Using cached torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
Collecting sentencepiece
  Using cached sentencepiece-0.2.1-cp313-cp313-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from transformers) (1.14.0)
Requirement already satisfied: numpy>=1.17 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from transformers) (2.4.2)
Requirement already satisfied: packaging>=20.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.14)
Requirement already satisfied: h11>=0.16 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Collecting setuptools<82 (from torch)
  Using cached setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\e l i t e b o o k\onedrive\documents\sem-6\venv\lib\site-packages (from jinja2->torch) (3.0.3)
Downloading torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.5/114.6 MB 367.3 kB/s eta 0:05:11
   ---------------------------------------- 0.5/114.6 MB 367.3 kB/s eta 0:05:11
   ---------------------------------------- 0.5/114.6 MB 367.3 kB/s eta 0:05:11
   ---------------------------------------- 0.5/114.6 MB 367.3 kB/s eta 0:05:11
   ---------------------------------------- 0.8/114.6 MB 362.3 kB/s eta 0:05:15
   ---------------------------------------- 0.8/114.6 MB 362.3 kB/s eta 0:05:15
   ---------------------------------------- 1.0/114.6 MB 416.1 kB/s eta 0:04:33
   ---------------------------------------- 1.0/114.6 MB 416.1 kB/s eta 0:04:33
   ---------------------------------------- 1.3/114.6 MB 426.1 kB/s eta 0:04:26
   ---------------------------------------- 1.3/114.6 MB 426.1 kB/s eta 0:04:26
    --------------------------------------- 1.6/114.6 MB 457.4 kB/s eta 0:04:08
    --------------------------------------- 1.6/114.6 MB 457.4 kB/s eta 0:04:08
    --------------------------------------- 1.6/114.6 MB 457.4 kB/s eta 0:04:08
    --------------------------------------- 1.8/114.6 MB 455.5 kB/s eta 0:04:08
    --------------------------------------- 1.8/114.6 MB 455.5 kB/s eta 0:04:08
    --------------------------------------- 2.1/114.6 MB 471.9 kB/s eta 0:03:59
    --------------------------------------- 2.4/114.6 MB 507.8 kB/s eta 0:03:41
    --------------------------------------- 2.4/114.6 MB 507.8 kB/s eta 0:03:41
    --------------------------------------- 2.6/114.6 MB 525.0 kB/s eta 0:03:34
    --------------------------------------- 2.6/114.6 MB 525.0 kB/s eta 0:03:34
   - -------------------------------------- 2.9/114.6 MB 534.5 kB/s eta 0:03:29
   - -------------------------------------- 2.9/114.6 MB 534.5 kB/s eta 0:03:29
   - -------------------------------------- 3.1/114.6 MB 544.5 kB/s eta 0:03:25
   - -------------------------------------- 3.1/114.6 MB 544.5 kB/s eta 0:03:25
   - -------------------------------------- 3.4/114.6 MB 556.6 kB/s eta 0:03:20
   - -------------------------------------- 3.4/114.6 MB 556.6 kB/s eta 0:03:20
   - -------------------------------------- 3.4/114.6 MB 556.6 kB/s eta 0:03:20
   - -------------------------------------- 3.7/114.6 MB 544.8 kB/s eta 0:03:24
   - -------------------------------------- 3.9/114.6 MB 554.4 kB/s eta 0:03:20
   - -------------------------------------- 3.9/114.6 MB 554.4 kB/s eta 0:03:20
   - -------------------------------------- 4.2/114.6 MB 568.5 kB/s eta 0:03:15
   - -------------------------------------- 4.5/114.6 MB 582.9 kB/s eta 0:03:09
   - -------------------------------------- 5.0/114.6 MB 630.8 kB/s eta 0:02:54
   - -------------------------------------- 5.2/114.6 MB 660.0 kB/s eta 0:02:46
   - -------------------------------------- 5.5/114.6 MB 667.4 kB/s eta 0:02:44
   - -------------------------------------- 5.5/114.6 MB 667.4 kB/s eta 0:02:44
   - -------------------------------------- 5.5/114.6 MB 667.4 kB/s eta 0:02:44
   -- ------------------------------------- 6.0/114.6 MB 686.8 kB/s eta 0:02:39
   -- ------------------------------------- 6.3/114.6 MB 704.3 kB/s eta 0:02:34
   -- ------------------------------------- 6.6/114.6 MB 709.2 kB/s eta 0:02:33
   -- ------------------------------------- 6.6/114.6 MB 709.2 kB/s eta 0:02:33
   -- ------------------------------------- 6.8/114.6 MB 699.8 kB/s eta 0:02:34
   -- ------------------------------------- 7.1/114.6 MB 722.1 kB/s eta 0:02:29
   -- ------------------------------------- 7.3/114.6 MB 722.5 kB/s eta 0:02:29
   -- ------------------------------------- 7.6/114.6 MB 743.7 kB/s eta 0:02:24
   -- ------------------------------------- 7.6/114.6 MB 743.7 kB/s eta 0:02:24
   -- ------------------------------------- 7.6/114.6 MB 743.7 kB/s eta 0:02:24
   -- ------------------------------------- 7.9/114.6 MB 726.7 kB/s eta 0:02:27
   -- ------------------------------------- 7.9/114.6 MB 726.7 kB/s eta 0:02:27
   -- ------------------------------------- 8.4/114.6 MB 735.2 kB/s eta 0:02:25
   --- ------------------------------------ 8.7/114.6 MB 756.1 kB/s eta 0:02:21
   --- ------------------------------------ 8.9/114.6 MB 755.5 kB/s eta 0:02:20
   --- ------------------------------------ 9.2/114.6 MB 763.2 kB/s eta 0:02:19
   --- ------------------------------------ 9.4/114.6 MB 782.9 kB/s eta 0:02:15
   --- ----------------------------------- 10.0/114.6 MB 804.3 kB/s eta 0:02:11
   --- ----------------------------------- 10.2/114.6 MB 807.4 kB/s eta 0:02:10
   --- ----------------------------------- 10.2/114.6 MB 807.4 kB/s eta 0:02:10
   --- ----------------------------------- 11.0/114.6 MB 844.2 kB/s eta 0:02:03
   --- ----------------------------------- 11.0/114.6 MB 844.2 kB/s eta 0:02:03
   --- ----------------------------------- 11.0/114.6 MB 844.2 kB/s eta 0:02:03
   --- ----------------------------------- 11.0/114.6 MB 844.2 kB/s eta 0:02:03
   ---- ---------------------------------- 11.8/114.6 MB 857.4 kB/s eta 0:02:00
   ---- ---------------------------------- 11.8/114.6 MB 857.4 kB/s eta 0:02:00
   ---- ---------------------------------- 11.8/114.6 MB 857.4 kB/s eta 0:02:00
   ---- ---------------------------------- 11.8/114.6 MB 857.4 kB/s eta 0:02:00
   ---- ---------------------------------- 12.3/114.6 MB 843.6 kB/s eta 0:02:02
   ---- ---------------------------------- 12.6/114.6 MB 845.2 kB/s eta 0:02:01
   ---- ---------------------------------- 12.6/114.6 MB 845.2 kB/s eta 0:02:01
   ---- ---------------------------------- 12.8/114.6 MB 840.3 kB/s eta 0:02:02
   ---- ---------------------------------- 12.8/114.6 MB 840.3 kB/s eta 0:02:02
   ---- ---------------------------------- 13.1/114.6 MB 837.7 kB/s eta 0:02:02
   ---- ---------------------------------- 13.4/114.6 MB 844.8 kB/s eta 0:02:00
   ---- ---------------------------------- 13.4/114.6 MB 844.8 kB/s eta 0:02:00
   ---- ---------------------------------- 13.9/114.6 MB 847.3 kB/s eta 0:01:59
   ---- ---------------------------------- 13.9/114.6 MB 847.3 kB/s eta 0:01:59
   ---- ---------------------------------- 13.9/114.6 MB 847.3 kB/s eta 0:01:59
   ---- ---------------------------------- 14.2/114.6 MB 840.2 kB/s eta 0:02:00
   ---- ---------------------------------- 14.2/114.6 MB 840.2 kB/s eta 0:02:00
   ---- ---------------------------------- 14.4/114.6 MB 827.7 kB/s eta 0:02:01
   ---- ---------------------------------- 14.4/114.6 MB 827.7 kB/s eta 0:02:01
   ---- ---------------------------------- 14.4/114.6 MB 827.7 kB/s eta 0:02:01
   ---- ---------------------------------- 14.7/114.6 MB 814.7 kB/s eta 0:02:03
   ---- ---------------------------------- 14.7/114.6 MB 814.7 kB/s eta 0:02:03
   ----- --------------------------------- 14.9/114.6 MB 811.9 kB/s eta 0:02:03
   ----- --------------------------------- 14.9/114.6 MB 811.9 kB/s eta 0:02:03
   ----- --------------------------------- 15.2/114.6 MB 801.9 kB/s eta 0:02:04
   ----- --------------------------------- 15.5/114.6 MB 812.0 kB/s eta 0:02:03
   ----- --------------------------------- 15.5/114.6 MB 812.0 kB/s eta 0:02:03
   ----- --------------------------------- 15.7/114.6 MB 799.3 kB/s eta 0:02:04
   ----- --------------------------------- 16.0/114.6 MB 808.8 kB/s eta 0:02:02
   ----- --------------------------------- 16.0/114.6 MB 808.8 kB/s eta 0:02:02
   ----- --------------------------------- 16.3/114.6 MB 801.1 kB/s eta 0:02:03
   ----- --------------------------------- 16.3/114.6 MB 801.1 kB/s eta 0:02:03
   ----- --------------------------------- 16.3/114.6 MB 801.1 kB/s eta 0:02:03
   ----- --------------------------------- 16.5/114.6 MB 787.4 kB/s eta 0:02:05
   ----- --------------------------------- 16.5/114.6 MB 787.4 kB/s eta 0:02:05
   ----- --------------------------------- 16.8/114.6 MB 778.9 kB/s eta 0:02:06
   ----- --------------------------------- 16.8/114.6 MB 778.9 kB/s eta 0:02:06
   ----- --------------------------------- 17.0/114.6 MB 770.4 kB/s eta 0:02:07
   ----- --------------------------------- 17.0/114.6 MB 770.4 kB/s eta 0:02:07
   ----- --------------------------------- 17.3/114.6 MB 769.7 kB/s eta 0:02:07
   ----- --------------------------------- 17.6/114.6 MB 776.3 kB/s eta 0:02:05
   ----- --------------------------------- 17.6/114.6 MB 776.3 kB/s eta 0:02:05
   ----- --------------------------------- 17.6/114.6 MB 776.3 kB/s eta 0:02:05
   ----- --------------------------------- 17.6/114.6 MB 776.3 kB/s eta 0:02:05
   ----- --------------------------------- 17.6/114.6 MB 776.3 kB/s eta 0:02:05
   ------ -------------------------------- 17.8/114.6 MB 751.6 kB/s eta 0:02:09
   ------ -------------------------------- 17.8/114.6 MB 751.6 kB/s eta 0:02:09
   ------ -------------------------------- 18.1/114.6 MB 747.9 kB/s eta 0:02:09
   ------ -------------------------------- 18.1/114.6 MB 747.9 kB/s eta 0:02:09
   ------ -------------------------------- 18.4/114.6 MB 742.8 kB/s eta 0:02:10
   ------ -------------------------------- 18.4/114.6 MB 742.8 kB/s eta 0:02:10
   ------ -------------------------------- 18.6/114.6 MB 742.4 kB/s eta 0:02:10
   ------ -------------------------------- 18.9/114.6 MB 750.1 kB/s eta 0:02:08
   ------ -------------------------------- 19.1/114.6 MB 748.9 kB/s eta 0:02:08
   ------ -------------------------------- 19.1/114.6 MB 748.9 kB/s eta 0:02:08
   ------ -------------------------------- 19.1/114.6 MB 748.9 kB/s eta 0:02:08
   ------ -------------------------------- 19.4/114.6 MB 743.0 kB/s eta 0:02:09
   ------ -------------------------------- 19.4/114.6 MB 743.0 kB/s eta 0:02:09
   ------ -------------------------------- 19.7/114.6 MB 742.6 kB/s eta 0:02:08
   ------ -------------------------------- 19.7/114.6 MB 742.6 kB/s eta 0:02:08
   ------ -------------------------------- 19.7/114.6 MB 742.6 kB/s eta 0:02:08
   ------ -------------------------------- 19.9/114.6 MB 734.3 kB/s eta 0:02:09
   ------ -------------------------------- 19.9/114.6 MB 734.3 kB/s eta 0:02:09
   ------ -------------------------------- 19.9/114.6 MB 734.3 kB/s eta 0:02:09
   ------ -------------------------------- 20.2/114.6 MB 729.4 kB/s eta 0:02:10
   ------ -------------------------------- 20.2/114.6 MB 729.4 kB/s eta 0:02:10
   ------ -------------------------------- 20.4/114.6 MB 723.9 kB/s eta 0:02:11
   ------- ------------------------------- 20.7/114.6 MB 728.9 kB/s eta 0:02:09
   ------- ------------------------------- 20.7/114.6 MB 728.9 kB/s eta 0:02:09
   ------- ------------------------------- 20.7/114.6 MB 728.9 kB/s eta 0:02:09
   ------- ------------------------------- 21.0/114.6 MB 723.6 kB/s eta 0:02:10
   ------- ------------------------------- 21.0/114.6 MB 723.6 kB/s eta 0:02:10
   ------- ------------------------------- 21.2/114.6 MB 719.5 kB/s eta 0:02:10
   ------- ------------------------------- 21.5/114.6 MB 725.0 kB/s eta 0:02:09
   ------- ------------------------------- 21.5/114.6 MB 725.0 kB/s eta 0:02:09
   ------- ------------------------------- 21.5/114.6 MB 725.0 kB/s eta 0:02:09
   ------- ------------------------------- 21.8/114.6 MB 720.9 kB/s eta 0:02:09
   ------- ------------------------------- 21.8/114.6 MB 720.9 kB/s eta 0:02:09
   ------- ------------------------------- 21.8/114.6 MB 720.9 kB/s eta 0:02:09
   ------- ------------------------------- 22.3/114.6 MB 728.4 kB/s eta 0:02:07
   ------- ------------------------------- 22.3/114.6 MB 728.4 kB/s eta 0:02:07
   ------- ------------------------------- 22.5/114.6 MB 738.6 kB/s eta 0:02:05
   ------- ------------------------------- 22.5/114.6 MB 738.6 kB/s eta 0:02:05
   ------- ------------------------------- 22.8/114.6 MB 735.0 kB/s eta 0:02:05
   ------- ------------------------------- 22.8/114.6 MB 735.0 kB/s eta 0:02:05
   ------- ------------------------------- 22.8/114.6 MB 735.0 kB/s eta 0:02:05
   ------- ------------------------------- 23.1/114.6 MB 734.1 kB/s eta 0:02:05
   ------- ------------------------------- 23.1/114.6 MB 734.1 kB/s eta 0:02:05
   ------- ------------------------------- 23.1/114.6 MB 734.1 kB/s eta 0:02:05
   ------- ------------------------------- 23.1/114.6 MB 734.1 kB/s eta 0:02:05
   ------- ------------------------------- 23.3/114.6 MB 728.8 kB/s eta 0:02:06
   -------- ------------------------------ 23.6/114.6 MB 734.9 kB/s eta 0:02:04
   -------- ------------------------------ 23.9/114.6 MB 740.8 kB/s eta 0:02:03
   -------- ------------------------------ 24.1/114.6 MB 744.0 kB/s eta 0:02:02
   -------- ------------------------------ 24.4/114.6 MB 750.6 kB/s eta 0:02:01
   -------- ------------------------------ 24.4/114.6 MB 750.6 kB/s eta 0:02:01
   -------- ------------------------------ 24.9/114.6 MB 751.7 kB/s eta 0:02:00
   -------- ------------------------------ 24.9/114.6 MB 751.7 kB/s eta 0:02:00
   -------- ------------------------------ 24.9/114.6 MB 751.7 kB/s eta 0:02:00
   -------- ------------------------------ 25.2/114.6 MB 750.1 kB/s eta 0:02:00
   -------- ------------------------------ 25.2/114.6 MB 750.1 kB/s eta 0:02:00
   -------- ------------------------------ 25.4/114.6 MB 749.4 kB/s eta 0:01:59
   -------- ------------------------------ 25.7/114.6 MB 751.6 kB/s eta 0:01:59
   -------- ------------------------------ 26.0/114.6 MB 755.9 kB/s eta 0:01:58
   -------- ------------------------------ 26.2/114.6 MB 764.4 kB/s eta 0:01:56
   -------- ------------------------------ 26.2/114.6 MB 764.4 kB/s eta 0:01:56
   -------- ------------------------------ 26.2/114.6 MB 764.4 kB/s eta 0:01:56
   -------- ------------------------------ 26.2/114.6 MB 764.4 kB/s eta 0:01:56

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# tokenizer
tokenizer = AutoTokenizer.from_pretrained(
    "cahya/t5-base-indonesian-summarization-cased"
)

# model
model = AutoModelForSeq2SeqLM.from_pretrained(
    "cahya/t5-base-indonesian-summarization-cased"
)

# tokenize input
inputs = tokenizer(
    df['clean_content'][0],
    max_length=512,
    truncation=True,
    return_tensors='pt'
)

# generate summary
summary_ids = model.generate(
    inputs['input_ids'],
    max_length=80,
    min_length=20,
    num_beams=4
)

# decode summary
summary = tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True
)

print(summary)

Loading weights: 100%|██████████| 260/260 [00:00<00:00, 4774.79it/s]

prakarsa pkp menunjukkan eksistensinya dengan kembali menggelar pameran properti bergengsi bertajuk pkp expo bertempat di grand batam mall pameran ini menjadi ajang bagi masyarakat untuk mendapatkan informasi komprehensif mengenai berbagai proyek hunian dan komersial unggulan pkp di lokasilokasi paling strategis di batam tepat hari ini jumat mei pkp hadir di atrium grand batam mall pkp

In [9]:
len(summary)

388

In [10]:
len(df['clean_content'][0])

1894

In [14]:
df['clean_content'][0]

'login untuk menyimpan artikel favorit kamu batam batamnews developer properti terbesar dan terpercaya di kota batam pt putera karyasindo prakarsa pkp menunjukkan eksistensinya dengan kembali menggelar pameran properti bergengsi bertajuk pkp expo bertempat di grand batam mall pameran ini menjadi ajang bagi masyarakat untuk mendapatkan informasi komprehensif mengenai berbagai proyek hunian dan komersial unggulan pkp di lokasilokasi paling strategis di batam tepat hari ini jumat mei pkp hadir di atrium grand batam mall pkp akan menggelar pameran pkp expo ini hingga mei mendatang dengan promo yang sangat luar biasa pkp menghadirkan lebih dari proyek properti mulai dari rumah ruko apartment hingga kavling yang tersebar di beberapa wilayah seperti batam center baloi tiban batuaji marina bandara dan nongsa mengusung tema promo bbm pameran properti terbesar di batam ini menjadi surga bagi para pencari rumah idaman dan investor yang ingin mendapatkan penawaran spesial dengan banyak bonus menguntungkan manager promosi pkp batam rio naldi menjelaskan pkp expo kali ini sangat spesial karena pkp memberikan banyak bonus menguntungkan penasaran apa saja bonusnya langsung saja mampir ke pameran kami konsumen yang sudah membeli unit berhak mengikuti undian berhadiah uang tunai ratusan juta rupiah dan undian berhadiah ini berlaku untuk banyak pemenang lho jadi peluang dapat nya sangat besar tambahnya bagi masyarakat yang berminat bisa segera booking unitnya dan dapatkan pilihan investasi terbaik anda hanya di pameran properti pkp expo kali ini selain itu juga bisa mengunjungi dan pkp store yang ada di lokasi yaitu di komplek ruko orchid park business centre komplek ruko mega legenda komplek ruko aji business centre dan komplek ruko trikarsa ekualita pasir putih follow us copyrightbatamnewscoidall rights reserveddikelola dan dikembangkan oleh pt batam media siber batamnews network'

c:\Users\E L I T E B O O K\OneDrive\Documents\sem-6\venv\Lib\site-packages\huggingface_hub\file_download.py:731: UserWarning: Not enough free disk space to download the file. The expected file size is: 891.64 MB. The target location C:\Users\E L I T E B O O K\.cache\huggingface\hub\models--cahya--t5-base-indonesian-summarization-cased\blobs only has 415.29 MB free disk space.
  warnings.warn(

In [13]:
df['links'][0]

'https://www.batamnews.co.id/berita-127180-pkp-expo-hadirkan-promo-bbm-di-grand-batam-mall.html'

#### pake api llm + long context

In [6]:
pip install google-genai

Collecting google-genaiNote: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'c:\Users\E L I T E B O O K\OneDrive\Documents\SEM 3\AI\.venv\Scripts\python.exe -m pip install --upgrade pip' command.

  Downloading google_genai-2.8.0-py3-none-any.whl (832 kB)
Collecting google-auth[requests]<3.0.0,>=2.48.1
  Downloading google_auth-2.55.0-py3-none-any.whl (252 kB)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from google-genai) (2.32.3)
Collecting sniffio
  Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting distro<2,>=1.7.0
  Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from google-genai) (9.0.0)
Collecting httpx<1.0.0,>=0.28.1
  Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Collecting typing-extensions<5.0.0,>=4.14.0
  Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Collecting pydantic<3.0.0,>=2.9.0
  Downloading pydantic-2.13.4-py3-none-any.whl (472 kB)
Collecting anyio<5.0.0,>=4.8.0
  Downloading anyio-4.14.0-py3-none-any.whl (123 kB)
Collecting websockets<17.0,>=13.0.0
  Downloading websockets-16.0-cp310-cp310-win_amd64.whl (178 kB)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (1.2.2)
Requirement already satisfied: idna>=2.8 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.10)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from google-auth[requests]<3.0.0,>=2.48.1->google-genai) (44.0.0)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Requirement already satisfied: cffi>=1.12 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from cryptography>=38.0.3->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (1.17.1)
Requirement already satisfied: pycparser in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.22)
Collecting httpcore==1.*
  Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Requirement already satisfied: certifi in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2024.8.30)
Collecting h11>=0.16
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Collecting pyasn1<0.7.0,>=0.6.1
  Downloading pyasn1-0.6.3-py3-none-any.whl (83 kB)
Collecting typing-inspection>=0.4.2
  Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Collecting pydantic-core==2.46.4
  Downloading pydantic_core-2.46.4-cp310-cp310-win_amd64.whl (2.1 MB)
Collecting annotated-types>=0.6.0
  Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.0)
Installing collected packages: pyasn1, typing-extensions, pyasn1-modules, h11, typing-inspection, pydantic-core, httpcore, google-auth, anyio, annotated-types, websockets, sniffio, pydantic, httpx, distro, google-genai
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 4.12.2
    Uninstalling typing-extensions-4.12.2:
      Successfully uninstalled typing-extensions-4.12.2
Successfully installed annotated-types-0.7.0 anyio-4.14.0 distro-1.9.0 google-auth-2.55.0 google-genai-2.8.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 pyasn1-0.6.3 pyasn1-modules-0.4.2 pydantic-2.13.4 pydantic-core-2.46.4 sniffio-1.3.1 typing-extensions-4.15.0 typing-inspection-0.4.2 websockets-16.0

In [13]:
pip install --upgrade pydantic

Requirement already satisfied: pydantic in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (2.13.4)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from pydantic) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from pydantic) (0.4.2)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from pydantic) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\e l i t e b o o k\onedrive\documents\sem 3\ai\.venv\lib\site-packages (from pydantic) (0.7.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.1.2 is available.
You should consider upgrading via the 'c:\Users\E L I T E B O O K\OneDrive\Documents\SEM 3\AI\.venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [14]:
from google import genai

client = genai.Client(api_key="AIzaSyBYrWDvXjC7yIdvzeycg25EnNe__3_4USk")
model_use = "gemini-2.5-flash"

ImportError: cannot import name 'Sentinel' from 'typing_extensions' (c:\Users\E L I T E B O O K\OneDrive\Documents\SEM 3\AI\.venv\lib\site-packages\typing_extensions.py)

In [ ]:
response = client.models.generate_content(
    model=model_use,
    contents=f"""
    Ringkas berita berikut menjadi 2-3 kalimat penting.

    {df['clean_content'][0]}
    """
)

print(response.text)

PT Putera Karyasindo Prakarsa (PKP) menggelar pameran properti bertajuk PKP Expo di atrium Grand Batam Mall mulai 24 hingga 26 Mei 2024. Pameran ini menawarkan informasi komprehensif mengenai berbagai proyek hunian dan komersial PKP di Batam. Dengan tema promo "BBM", PKP Expo memberikan banyak bonus menguntungkan dan kesempatan undian berhadiah uang tunai ratusan juta rupiah bagi para pembeli.

In [ ]:
query = "ekonomi"

results = df[
    df['clean_full_text'].str.contains(query, case=False, na=False)
]

results = results.reset_index(drop=True)

combined_text = '\n\n---\n\n'.join(
    results['content'].head(5).tolist()
)
print(results.columns)

Index(['Unnamed: 0', 'title', 'news_type', 'content', 'published_date',
       'links', 'full_text', 'clean_content', 'clean_title',
       'clean_full_text'],
      dtype='str')

In [ ]:
#per artikel

response_1 = client.models.generate_content(
    model=model_use,
    contents=f"""
    Anda adalah analis berita ekonomi untuk pekerja BPS 

    Tugas:
    Buat ringkasan singkat dari kumpulan berita berikut

    Fokus:
    - data ekonomi
    - nominal uang
    - persentase
    - tren investasi
    - hubungan antar negara terkait ekonomi
    - insight utama

    Aturan:
    - gunakan bahasa semi formal dan padat
    - jangan mengulang informasi
    - jika data tidak tersedia, jangan mengarang
    - buat dalam bentuk bullet points
    - beri tahu rentang berita di dapat dari kapan saja

    Format penulisan:
    - Ringkasan singkat terkait apa yang terjadi
    - insight utama dalam bentuk bullet points

    Berita:
    {results['clean_content'][0]}
    Tanggal keluar berita:
    {results['published_date'][0]}
    """
)

print(response_1.text)

Halo rekan-rekan analis BPS,

Berikut adalah ringkasan singkat dari berita ekonomi yang diterbitkan pada Sabtu, 09 Mei 2026.

BP Batam terus memperkuat posisinya sebagai pusat investasi regional melalui peningkatan kolaborasi ekonomi dengan India. Langkah strategis ini diwujudkan melalui kunjungan kerja Deputi Bidang Investasi BP Batam ke Konsul Jenderal India di Medan. Hubungan ekonomi antara Batam dan India menunjukkan tren positif yang signifikan, dengan India kini menjadi tujuan ekspor terbesar ketiga bagi Batam. Sebagai tindak lanjut, kedua pihak sepakat untuk menyelenggarakan forum bisnis hibrida guna mempertemukan pelaku industri dan memetakan kebutuhan rantai pasok secara lebih rinci.

**Insight Utama:**

*   **Tren Investasi & Hubungan Ekonomi:** Hubungan ekonomi Batam dan India menunjukkan tren positif yang signifikan, menandai kepercayaan dunia usaha India terhadap daya saing Batam. India telah menjelma menjadi mitra strategis dan tujuan ekspor terbesar ketiga bagi Batam, dengan kedua negara memandang peluang untuk tumbuh bersama.
*   **Data Ekonomi, Nominal Uang, & Persentase:** Meskipun berita menyebutkan adanya data investasi India di Batam (mencapai angka miliar Rupiah), realisasi investasi tertinggi pada tahun tertentu, nilai ekspor Batam ke India pada Kuartal I (USD juta), serta persentase kontribusinya terhadap total ekspor Batam, angka nominal dan persentase spesifik dari data-data tersebut tidak disajikan dalam berita ini.
*   **Fokus Strategis BP Batam:** BP Batam secara proaktif memantapkan ekosistem investasi melalui pengembangan kawasan industri, logistik, dan perdagangan internasional. Sektor potensial untuk kolaborasi mencakup manufaktur, energi terbarukan, maritim, dan penguatan rantai pasok industri.
*   **Daya Tarik Investasi Batam:** Konsul Jenderal India menggarisbawahi keunggulan geografis Batam yang dekat dengan Singapura, kepemimpinan yang kuat, serta statusnya sebagai Kawasan Perdagangan Bebas (Free Trade Zone) sebagai daya tarik utama bagi investor.
*   **Langkah Konkret Diplomasi Ekonomi:** Kedua pihak berencana menyelenggarakan forum presentasi bisnis secara hibrida. Forum ini akan mempertemukan pengelola kawasan industri di Batam dengan jaringan kamar dagang India, serta bertujuan untuk memetakan kebutuhan rantai pasok ekspor-impor secara detail melalui identifikasi produk berbasis kode Harmonized System (HS).

kalo user minta data berdasarkan tanggal

kalo user minta data berdasarkan keywoard

In [ ]:
kalo user minta data berdasarkan tanggal dan keyword

##### pake api llm + long context + chunking

#### pake api llm + rag

cocoknya untuk pencarian berbasis keyword dan jawabannya to the point, sedangkan long context lebih cocok untuk summary, karena rag pake chunk jadi ada kemungkinan kalo context yang di tengah dilewati/terpotong karena chunking, kecuali untuk hierarchical summarize.